### ISSUE TITLE
Rubygems?

### ISSUE THREAD

**Issue by greenbigfrog** [Quintus/cinch-plugins#12]
Are you still thinking about adding your plugins to rubygems?

**Comment by Quintus** [comment]
I think so, but currently, I think the code is not in a releasable state. Some things are resolved quite hacky, and I’m eternally uncontent of how the logplus plugin is implemented. Then I’ve some other plugins on my mind I’d like to implement first, so the answer is: Yes, but now now...

Vale,
Quintus
